### ISSUE TITLE
不能正常使用

### ISSUE THREAD

**Issue by Japerz12138** [Sucareto/ESP32-CardReader#2]
大佬很抱歉又来打扰你了！

这两天定做的PCB到了，全部都装在一起之后PN532亮灯，SSD1306显示一个断开连接的图标，HIGH，和左下角的TN32MSEC003S。
在这之前已经上传TEST试过了，读卡时可以在串口监视器里看到数据，但是使用这个项目里的就不太行(
测试了其他的功能，比如OTA Update都没问题。
测试的游戏有Chunithm New Plus和SDVX EG S2，中二的话是已经在segatools.ini里的aime项添加了enable=0。有使用 amdaemon ，config_common.json 内找不到 aime 项。中二的自检startup页显示找不到读卡器设备。
SDVX是确实还没搞清楚怎么用，如果大佬知道还请多指教.jpg
COM设置的是1，high_baudrate为high。驱动已确定安装。
丢卡上去SSD1306不显示任何东西，那俩插头始终是断开状态（无论我有没有连接到电脑上）

非常抱歉问这么多问题，希望可以帮帮2333

**Comment by Sucareto** [comment]
在 SDHD，`aime` 设置已经分离到 `config_cvt.json` 和 `config_sp.json`，检查你启动的模式是哪一种（sp/cvt)，再查看对应的配置文件确认 `high_baudrate` 的状态。
那个 `usb_connect` 标志，是只有在主控收到串口信息才会显示为连接状态。
Aime 读卡器不支持 SDVX。

**Comment by Japerz12138** [comment]
实在是太感谢了，帮了大忙了！在service mode里查看了是CVT模式，config_cvt.json里的port是4，对应high_baudrate。成功刷卡并显示NFC标志，Aime初期化GOOD！
成功做出来这个刷卡器真的学到了很多东西，也非常感谢大佬一直的帮助！这个项目真的非常棒！
祝安！
