### ISSUE TITLE
BUG反馈

### ISSUE THREAD

**Issue by XaviorShen** [Sucareto/ESP32-CardReader#3]
![image](https://user-images.githubusercontent.com/58615985/229357544-12ee0734-7c43-4e48-b732-b665dc64bc6d.png)
Aime 模式这边写错了。
“ON：使用 38400 波特率初始化，固件版本是 TN32MSEC003S
OFF：使用 115200 波特率初始化，固件版本是 837-15396”
这里ON和OFF正好写反了

**Comment by Sucareto** [comment]
感谢提醒~
这部分逻辑写得有点混乱，之后重写再一起提交好了~

**Comment by Sucareto** [comment]
已修正。

**Comment by XaviorShen** [comment]
好耶
