### ISSUE TITLE
找不到<PN532_SPI.h>

### ISSUE THREAD

**Issue by Ekac00** [Sucareto/ESP32-CardReader#5]
编译时ide提示
_In file included from E:\Ekac\ESP32-CardReader\ESP32-CardReader.ino:1:
E:\Ekac\ESP32-CardReader\Aime_Reader.h:45:10: fatal error: PN532_SPI.h: No such file or directory
 #include <PN532_SPI.h>
          ^~~~~~~~~~~~~
compilation terminated._

**Comment by animevietsub** [comment]
Make sure you have installed [**PN532_SPI library**](https://github.com/Sucareto/Aime_Reader_PN532) from @Sucareto

**Comment by Sucareto** [comment]
请按照 [PN532](https://github.com/elechouse/PN532) 或 [Aime_Reader_PN532](https://github.com/Sucareto/Aime_Reader_PN532) 的提示安装依赖的 PN532 库。

**Comment by Ekac00** [comment]
感谢~

**Comment by Ekac00** [comment]
还有一个问题，现在编译会出现
_In file included from E:\Ekac\ESP32-CardReader\ESP32-CardReader.ino:1:
E:\Ekac\ESP32-CardReader\Aime_Reader.h:2:17: note: #pragma message: 当前的开发板是 ESP32
 井号pragma message "当前的开发板是 ESP32"
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from c:\Users\23963\Documents\Arduino\libraries\FastLED\src/FastLED.h:75,
                 from E:\Ekac\ESP32-CardReader\Aime_Reader.h:41,
                 from E:\Ekac\ESP32-CardReader\ESP32-CardReader.ino:1:
c:\Users\23963\Documents\Arduino\libraries\FastLED\src/fastspi.h:157:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output
 井号      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~_
但是不会停止编译

**Comment by Sucareto** [comment]
这些并不是错误，只是提示。

**Comment by Ekac00** [comment]
ok

**Comment by Ekac00** [comment]
我能不能在b站上发一期关于你的读卡器的视频？

**Comment by Ekac00** [comment]
还有就是_AimePad.ai_提示少了一个名叫_title.png_的文件

**Comment by Sucareto** [comment]
> 我能不能在b站上发一期关于你的读卡器的视频？

我并无意宣传这个项目，但如果你愿意基于自己的理解来介绍一下的话也很欢迎~

> 还有就是_AimePad.ai_提示少了一个名叫_title.png_的文件

这个文件太久了，我也找不到那个图片了。应该就是 Aime 的标志图片，或许是这个 [title.png](https://my-aime.net/assets/lang/ja/img/common/title.png) 裁剪一下就行。
如果你打算自己做的话，还是推荐改成自己喜欢的图案啦~

**Comment by Ekac00** [comment]
ok
感谢感谢
