### ISSUE TITLE
请教一些小问题

### ISSUE THREAD

**Issue by Ekac00** [Sucareto/ESP32-CardReader#6]
我会在这里留下一些使用中的小问题，其他人也可以在这留言

**Comment by Ekac00** [comment]
目前我遇到的问题：
1. 使用M1T工具识别不到读卡器（所有拨码开关都在正确的位置）
2. 前面板（就是上次我发issues找不到title.png的矢量图）的尺寸是多少？

**Comment by Sucareto** [comment]
如果是使用本项目的 PCB，连接 [MifareOneTool](https://github.com/xcicode/MifareOneTool) 需要检查以下设置：
- TTL 拨码开关需要全部设为 ON
- PN532 模块的拨码开关需要按照 PCB 上面的指示，设为 HSU 模式
- 在断电情况下完成以上拨码切换操作，切换完成后再接入电脑，检查 COM 是否正确识别
- 启动 MifareOneTool，高级操作模式 -> 设备控制 -> 检测设备

盖板设计图 [AimePad.ai](https://github.com/Sucareto/ESP32-CardReader/blob/main/PCB/AimePad.ai) 仅用作参考，你可以按照自己的想法修改创作。
我使用的尺寸是 99.060 mm x 63.500 mm，使用 [嘉立创 EDA](https://lceda.cn/editor) 打开 [PCB 设计图](https://github.com/Sucareto/ESP32-CardReader/blob/main/PCB/PCB_ESP32S-PN532-v2.json) 也可以看到尺寸。

**Comment by Ekac00** [comment]
只通电时8个灯不亮正常吗？

**Comment by Ekac00** [comment]
MifareOneTool还是找不到，设备管理器可以看见ch340
![image](https://github.com/Sucareto/ESP32-CardReader/assets/97278930/c2e3b235-0dbe-464b-ae58-fb7372f84889)

**Comment by Sucareto** [comment]
> 只通电时8个灯不亮正常吗？

正常的。



> MifareOneTool还是找不到，设备管理器可以看见ch340 ![image](https://user-images.githubusercontent.com/97278930/275496083-c2e3b235-0dbe-464b-ae58-fb7372f84889.png)

或者换一下别的 COM ？比如 COM3 怎么样

**Comment by Ekac00** [comment]
好像还不行(っ °Д °;)っ

**Comment by Sucareto** [comment]
未切换为 TTL 模式时，读卡器是否正常工作？如果没有，那可能是 PN532 模块连接出现问题；如果正常，切换为其他 COM 口重新试一下，或者调整一下 PN532 的拨码开关？

**Comment by Ekac00** [comment]
因为HDD还没下好，现在只通电PN532会亮灯

**Comment by Sucareto** [comment]
可以刷入 [ReaderTest.ino](https://github.com/Sucareto/Arduino-Aime-Reader/blob/main/tools/ReaderTest/ReaderTest.ino) 测试读卡器是否正常。

**Comment by Ekac00** [comment]
![image](https://github.com/Sucareto/ESP32-CardReader/assets/97278930/00e423dd-5c5a-48b7-ad68-39bc8e55d4a7)
为什么fes连不上读卡器

**Comment by Ekac00** [comment]
使用[ReaderTest.ino](https://github.com/Sucareto/Arduino-Aime-Reader/blob/main/tools/ReaderTest/ReaderTest.ino)测试可以读卡

**Comment by Ekac00** [comment]
自己摸索着成功了，这是一个非常好的项目，非常感谢作者！

**Comment by Ekac00** [comment]
现在就想知道m1t连不上的问题

**Comment by Ekac00** [comment]
还有就是sinmai连上读卡器后8个灯不亮

**Comment by Sucareto** [comment]
> 使用[ReaderTest.ino](https://github.com/Sucareto/Arduino-Aime-Reader/blob/main/tools/ReaderTest/ReaderTest.ino)测试可以读卡

那硬件部分应该是没问题的。

> 现在就想知道m1t连不上的问题

要确保 PN532 正确切换为 HSU 模式，且 PCB 上的 TTL 开关全部为 ON 后，才可以通过串口连接到 PN532 模块。
或者可以换用其他工具试试看？如果有 USB 转 TTL 线的话，也可以试试单独连接 PN532 是否可以正确识别。

> 还有就是sinmai连上读卡器后8个灯不亮

需要在 segatools 关闭读卡器模拟，才能连接到实体读卡器。连接成功后，读卡器灯光由游戏控制，可以进测试菜单测试灯光。
