### ISSUE TITLE
fatal error: ArduinoJson.h: No such file or directory  #include "ArduinoJson.h"

### ISSUE THREAD

**Issue by Mari-2233** [Sucareto/ESP32-CardReader#7]
In file included from C:\Users\Administrator\Desktop\ESP32-CardReader\Aime_Reader.h:57,
                 from C:\Users\Administrator\Desktop\ESP32-CardReader\ESP32-CardReader.ino:1:
C:\Users\Administrator\Desktop\ESP32-CardReader\src\wrappers.h:9:10: fatal error: ArduinoJson.h: No such file or directory
 #include "ArduinoJson.h"
          ^~~~~~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: ArduinoJson.h: No such file or directory

**Comment by Sucareto** [comment]
You need to install the ArduinoJson library from the menu of the Arduino IDE.
Please refer to the operating steps:
https://stackoverflow.com/questions/50543488/arduinojson-h-no-such-file-or-directory-arduino

**Comment by Mari-2233** [comment]
In file included from C:\Users\Administrator\Desktop\ESP32-CardReader\ESP32-CardReader.ino:1:
C:\Users\Administrator\Desktop\ESP32-CardReader\Aime_Reader.h:2:17: note: #pragma message: 当前的开发板是 ESP32
 #pragma message "当前的开发板是 ESP32"
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from c:\Users\Administrator\Documents\Arduino\libraries\FastLED\src/FastLED.h:75,
                 from C:\Users\Administrator\Desktop\ESP32-CardReader\Aime_Reader.h:41,
                 from C:\Users\Administrator\Desktop\ESP32-CardReader\ESP32-CardReader.ino:1:
c:\Users\Administrator\Documents\Arduino\libraries\FastLED\src/fastspi.h:157:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output
 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Sketch uses 313861 bytes (23%) of program storage space. Maximum is 1310720 bytes.
Global variables use 21704 bytes (6%) of dynamic memory, leaving 305976 bytes for local variables. Maximum is 327680 bytes.

**Comment by Mari-2233** [comment]
Is that right？

**Comment by Sucareto** [comment]
Yes, this is the normal output content. Next just check if it is working properly.

**Comment by Mari-2233** [comment]
thank you.
