### ISSUE TITLE
emm...  I think it's a very strange mistake, and I'm not sure when he'll show up

### ISSUE THREAD

**Issue by Mari-2233** [Sucareto/ESP32-CardReader#8]
This image was taken normally but without the main program open.
![P40116-215137](https://github.com/Sucareto/ESP32-CardReader/assets/104679134/f4c4ecbf-1836-4601-b08a-4fdf7a2a8f42)
This image was taken with the main program open normally.
![P40116-215314](https://github.com/Sucareto/ESP32-CardReader/assets/104679134/7e08330f-0170-449f-94dc-2b433d2444ca)
The exception I'm talking about is showing only what the red arrow points to (my drawing is a little abstract, but it looks something like this).
![P20240116221055](https://github.com/Sucareto/ESP32-CardReader/assets/104679134/4f13cbcd-fd88-4f95-8e80-aa824f238904)
It's worth noting that I'm also not sure when this error occurred.

**Comment by Sucareto** [comment]
In the last picture, that icon is defined as rf_off in the source code and appears when the programme fails to detect the PN532 Firmware Version, which usually means that the PN532 connection is unstable.
https://github.com/Sucareto/ESP32-CardReader/blob/main/ESP32-CardReader.ino#L43C38-L43C38

You can use [ReaderTest.ino](https://github.com/Sucareto/Arduino-Aime-Reader/blob/main/tools/ReaderTest/ReaderTest.ino) to test if the card reader is working correctly.
If no error occurs after several tests, then you can ignore the problem.

**Comment by Mari-2233** [comment]
Ok, I see.
